#!/bin/bash
export STACK_TYPE="CDH"
export STACK_VERSION="7.0.0"
export STACK_BASEURL="http://s3.amazonaws.com/dev.hortonworks.com/CFM/centos7/1.x/BUILDS/1.1.0.0-34/tars/parcel"
export PARCELS_NAME="CFM-1.1.0.0-el7.parcel"
export STACK_REPOID="miss"
export STACK_REPOSITORY_VERSION="1.1.0.0"
export CLUSTERMANAGER_VERSION="7.x.0"
export CLUSTERMANAGER_BASEURL="http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/1296423/cm7/7.x.0/redhat7/yum/"
export CLUSTERMANAGER_GPGKEY="http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/1296423/cm7/7.x.0/redhat7/yum/RPM-GPG-KEY-cloudera"
export SALT_VERSION="2017.7.5"
export SALT_PATH="/opt/salt_${SALT_VERSION}"
export PYZMQ_VERSION="14.5.0"
export PYTHON_APT_VERSION="1.1.0_beta1ubuntu0.16.04.1"
export OS=centos7
export OS_TYPE=redhat7
export TAG=centos-76
export DIR=centos7.6
export PARCELS_ROOT=/opt/cloudera/parcels
export PRE_WARM_PARCELS='[["CFM-1.1.0.0", "CFM-1.1.0.0-el7.parcel","http://s3.amazonaws.com/dev.hortonworks.com/CFM/centos7/1.x/BUILDS/1.1.0.0-34/tars/parcel"]]'

DOCKER_ENVS="PARCELS_NAME=${PARCELS_NAME} STACK_REPOSITORY_VERSION=${STACK_REPOSITORY_VERSION} STACK_TYPE=${STACK_TYPE} CLUSTERMANAGER_VERSION=${CLUSTERMANAGER_VERSION} CLUSTERMANAGER_BASEURL=${CLUSTERMANAGER_BASEURL} CLUSTERMANAGER_GPGKEY=${CLUSTERMANAGER_GPGKEY} OS=${OS} OS_TYPE=${OS_TYPE} SALT_VERSION=${SALT_VERSION} SALT_PATH=${SALT_PATH} PYZMQ_VERSION=${PYZMQ_VERSION} PYTHON_APT_VERSION=${PYTHON_APT_VERSION} TRACE=1"
DOCKER_BUILD_ARGS=$(echo ${DOCKER_ENVS} | xargs -n 1 echo "--build-arg " | xargs)
docker build --build-arg PRE_WARM_PARCELS="${PRE_WARM_PARCELS}" ${DOCKER_BUILD_ARGS} -t registry.eng.hortonworks.com/cloudbreak/${TAG}:$(date +%Y-%m-%d) -f docker/${DIR}/Dockerfile . | tee build.log